### ISSUE TITLE
Question about typebatch

### ISSUE THREAD

**Issue by wenjiezeng08** [vandijklab/CINEMA-OT#10]
Thank you for creating this great package!

I have a question based on your tutorial https://github.com/vandijklab/CINEMA-OT/blob/main/cinemaot_tutorial.ipynb, and my question is about the "typebatch".

 If I understand the process correctly, after running CINEMIA-OT, you clustered cells based on the response matrix, and they fell into two clusters (i.e., typebatches), CD4 T cells and monocytes, in your example. However, in the graph on the right, which was colored by original cell type, there are multiple other cell types. 

My questions is, what does "typebatch" mean here? Why there are only two cell types in the typebatch variable, when there are multiple other cell types? Does this mean that CD4 T cells and monocytes are main ones driving the classification of typebatches, cells with similar response were clustered in the same cluster, and therefore the typebatches were named after the main cell types in the batch? Based on this result, can I say that CD4 T cells and monocytes are the ones that are most responsive to the treatment (and therefore can be considered as interventional targets)?

**Comment by MingzeDong** [comment]
Thanks for the interest in the package! Your understanding is correct, we named the response clusters based on the most abundant cell type within each of them. But I would not say that CD4 T cells and monocytes are the two cell types most responsive to the treatment, they are just of high number. For example, CD8 T cells have a highly similar response pattern to CD4 T cells. 

Hopefully this helps :)

**Comment by wenjiezeng08** [comment]
> Thanks for the interest in the package! Your understanding is correct, we named the response clusters based on the most abundant cell type within each of them. But I would not say that CD4 T cells and monocytes are the two cell types most responsive to the treatment, they are just of high number. For example, CD8 T cells have a highly similar response pattern to CD4 T cells.
> 
> Hopefully this helps :)

Hi Mingze, thank you so much for the clarification, this helps a lot! So based on this interpretation, can I rename the cells clusters as CD4 T cell dominant batch and monocyte dominant batch respectively, in your example? 

I have a further question on the downstream DEG analysis on the response matrix. First, what does the score in the y-axis mean? Second, should I interpret it is the genes that have driven the response, or it is the perturbation effect that changed the gene expression? Basically, my question is, change in gene expression and change in condition, which should be interpreted as the cause and which as the effect? Or the interpretation will vary case-by-case?

My scenario is used CINEMA-OT to analyze pbmcs from patients and healthy controls and my goal for this analysis is to identify causal genes of the disease conditions.

**Comment by MingzeDong** [comment]
The score is the "differential expression score" implemented in scanpy. For your second question, the method basically identifies the genes changed with the condition. Therefore both of your described case can happen in practice. Specifically, a disease may be the result of increased gene A, and the disease further affects expression of genes B,C,D,E. In our work, we mostly worked on experimentally perturbed data, where the interpretation would be straightforward (the condition is caused by experiments, not genes). Indeed things will be more complicated in the disease case and would require specific interpretation.

**Comment by wenjiezeng08** [comment]
> The score is the "differential expression score" implemented in scanpy. For your second question, the method basically identifies the genes changed with the condition. Therefore both of your described case can happen in practice. Specifically, a disease may be the result of increased gene A, and the disease further affects expression of genes B,C,D,E. In our work, we mostly worked on experimentally perturbed data, where the interpretation would be straightforward (the condition is caused by experiments, not genes). Indeed things will be more complicated in the disease case and would require specific interpretation.

Thank you so much. This makes sense to me and I have no more questions
