### ISSUE TITLE
Do you have a snippet to reproduce the comparisons made on Fig. 3?

### ISSUE THREAD

**Issue by JeanRadig** [vandijklab/CINEMA-OT#12]
Hello! 

I would like to be able to reproduce the comparisons as done on Fig. 3. In particular, I would be interested in seeing how you have ran cellOT on your data. Do you have some code available to reproduce the simulation?

Thanks in advance!

**Comment by MingcanTang** [comment]
I also want it!

**Comment by MingzeDong** [comment]
Hi, the code for generating the simulation data is uploaded as "simulation.py". CellOT was run on the principal components of log normalized expression for the simulated datasets. Antonio @ahof1704 should have the code. Let me know if there are further problems!
