### ISSUE TITLE
Cannot find TR.txt, HLA.txt, IG.txt

### ISSUE THREAD

**Issue by paolaporracciolo** [vandijklab/CINEMA-OT#13]
Hi, 

I read your paper and I find the algorithm and analysis very interesting.
However, when I try to reproduce your tutorial, I cannot find the following files: TR.txt, HLA.txt, IG.txt

Thank you

**Comment by MingzeDong** [comment]
They are not necessary for the analysis (at least in the tutorial). Nevertheless, the files are uploaded here for reference: 
[TR.txt](https://github.com/user-attachments/files/17548713/TR.txt)
[HLA.txt](https://github.com/user-attachments/files/17548714/HLA.txt)
[IG.txt](https://github.com/user-attachments/files/17548715/IG.txt)

**Comment by paolaporracciolo** [comment]
Thank you very much for your answer and for sharing your data.

I see it is not strictly necessary, however I want to reproduce your exact results, and for that it appears that you filter your vars by filterlist which is obtained by the following line:
`filterlist = list(set(TR['Approved symbol'].values.tolist()) | set(HLA['Approved symbol'].values.tolist()) | set(IG['Approved symbol'].values.tolist()))`
which needs the three files. 

Thank you again,
Paola
