### ISSUE TITLE
Can't import cinemaot module after pip install from git

### ISSUE THREAD

**Issue by ethanweinberger** [vandijklab/CINEMA-OT#2]
Hi CINEMA-OT team,

First off, thanks for releasing your method in such a nice package! I'm excited to try it out on some scRNA-seq data that I've been working with.

I'm opening this issue to flag some potential issues with your package setup: In particular, this morning I tried to install the CINEMA-OT package in a clean conda environment using the instructions in the README (i.e., the pip+git command). The command runs without any errors, however I'm still not able to import the `cinemaot` module. When I look in my conda environment's site-packages directory, I see that a folder `cinemaot-0.0.1.dist-info` has been created, though the package itself is missing (I would expect another folder just named `cinemaot`).

I'm able to successfully import CINEMA-OT's dependencies (scanpy etc.), so I think there may be a problem somewhere in the structure of the package.

**Comment by MingzeDong** [comment]
Hi,

Thank you for trying our method and sorry for the late reply! We updated the package setup last month and tested it on our own virtual environments. Now it can be installed directly via pip. The issue should be resolved but let us know if you encounter further problems.
