### ISSUE TITLE
Individual treatment effect matrices

### ISSUE THREAD

**Issue by domcke** [vandijklab/CINEMA-OT#4]
It is not clear to me from the tutorial how to extract the cell x gene 'Individual treatment effect' matrices for downstream clustering, DE analysis etc. Would you mind sharing some code for that? Thanks!

**Comment by MingzeDong** [comment]
Hi, the individual treatment effect matrix is stored in the AnnData "de", which is an output of co.cinemaot.cinemaot_unweighted in the tutorial. Happy to answer further questions.

**Comment by domcke** [comment]
Thanks so much for your quick response! I do have two questions:

1) The main part that is not clear to me is how I can get the DE genes between the OT-matched perturbed and non-stimulated cells (not e.g. Monocyte vs rest within the perturbed group like in your example), since the "de" object only contains perturbed cells, and I accordingly can’t do e.g. 
```
sc.tl.rank_genes_groups(de, 'perturbation', method='t-test')
```

I see that below you calculate        

de_c = sc.AnnData(subset_mock.X.toarray()-de.X) ; where "de" in this case has the dimensions of "No stimulation", not the perturbed dimensions as above, and then you assign it the respective perturbation class.

I assume it would not be correct to do this for my purpose?: 
```
response = adata_[adata_.obs['perturbation'].isin(['Control']),:]
sc.pp.pca(adata_)
cf, ot, de = co.cinemaot.cinemaot_unweighted(adata_,obs_label='perturbation', ref_label=‘Control', expr_label='Perturbation_X',mode='parametric',thres=0.5,smoothness=1e-4,eps=1e-2,preweight_label=None)
subset_mock = adata_[adata_.obs['perturbation'].isin(['Control']),:]
de_c = sc.AnnData(subset_mock.X.toarray()-de.X)
de_c.obs['perturbation'] = 'Perturbation_X'
de_c.var_names = subset_mock.var_names
response = sc.concat([response,de_c])
sc.pp.pca(response)
sc.pp.neighbors(response)
sc.tl.umap(response)
sc.tl.rank_genes_groups(response, 'perturbation', method='t-test’)
```
Any pointers on how to extract DE genes between OT-matched perturbed and non-stimulated cells would be appreciated!


2) What is the preweight_label parameter in co.cinemaot.cinemaot_unweighted? I assume this normalizes across different cell numbers per cell type in your example. If I only have one cell type, but different experimental batches with different cell numbers but similar ratios of perturbed and control cells, I assume the correct setting here would be None?

Thanks for your help!

**Comment by MingzeDong** [comment]
To get the OT-matched unstimulated cells in the tutorial, you can use command "adata[adata.obs['perturbation'].isin(['IFNb'])].X-de.X". This returns the counterfactual population of unstimulated cells in the "stimulated space". For your purpose you can concatenate this matrix with the original normalized count matrix of the stimulated cells and do downstream DE analysis. This means your codes are actually right in your setting.

However, CINEMA-OT is designed for identifying causal pairs, and your implementation "sc.tl.rank_genes_groups" still uses the unpaired statistical test, in which case I anticipate using the CINEMA-OT won't make much difference. Instead, you may consider running paired statistical test (scipy.stats.wilcoxon) on the de matrix. This should be the correct way to identify differential expressed genes in your setting using CINEMA-OT. However, it should be noted that more theoretical work is needed for establishing the p-values accounting for the uncertainty of CINEMA-OT matching.

For the second question, in principle the experimental batch is also a confounder here. Therefore it is correct to set the preweight_label to be the batch label. However, if the ratios of perturbed and control cells are similar (as you described), the result should not be much different if we set the preweight label to None.

**Comment by domcke** [comment]
Great, that is very helpful, thanks for clarifying!
