### ISSUE TITLE
module 'cinemaot' has no attribute 'utils'

### ISSUE THREAD

**Issue by ggyycho** [vandijklab/CINEMA-OT#6]
Hi
After reading your paper, I thought it was a very useful tool, so I'm using it for my data.
Installation proceeded without problem, but the error below occurred :

co.utils.assignleiden(de,'celltype','leiden','typebatch')
AttributeError: module 'cinemaot' has no attribute 'utils'

I'll be waiting for your feedback. Thank you.

**Comment by MingzeDong** [comment]
Thanks! In the current release we are not importing "utils" when we import the package. Therefore you should directly use "from cinemaot import utils" and use "utils.assignleiden(de,'celltype','leiden','typebatch')" instead. Let me know if you encounter further problems.

**Comment by harishvenkatachalapathy** [comment]
Just wanted to notify you that the tutorial notebook still seems to have a co.utils call that throws an error. It's right after the Leiden clustering.
